apiVersion: v1
kind: Pod
metadata:
  name: iperf-server
spec:
  containers:
  - name: server
    image: iperf:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: iperf-client
spec:
  containers:
  - name: client
    image: iperf:latest
