apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hello-flask-deployment.yaml
- hello-flask-svc.yaml
- hello-flask-route.yaml

components:
- ./hello-flask-pipeline/

namespace: app1-dev
