apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./acs-ci-config
- ./app1-dev-ns
- ./docker-httpd-deployment
- ./docker-httpd-pipeline
- ./hello-flask-deployment
- ./hello-flask-pipeline
namespace: app1-dev
