apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-cop/gitops-catalog/openshift-pipelines-tasks/rollout-restart/base?ref=main
  - pipeline-docker-httpd.yaml
