apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: docker-httpd-
  namespace: app1-dev
spec:
  pipelineRef:
    name: docker-httpd
  workspaces:
    - name: workspace # this workspace name must be declared in the Pipeline
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
              
