apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: docker-httpd
spec:
  params:
  - default: https://github.com/martineg/ocp-labs.git
    name: GIT_REPO
    type: string
  - default: main
    name: GIT_REVISION
    type: string
  - default: httpd
    name: APP_NAME
    type: string
  - default: image-registry.openshift-image-registry.svc:5000/app1-dev/httpd
    name: IMAGE__NAME
    type: string
  - default: acs-token
    name: ACS_ENDPOINT
    type: string
  - default: acs-token
    name: ACS_API_TOKEN
    type: string
  - default: docker-httpd
    name: CONTEXT_DIR
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: refspec
      value: ""
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: crtFileName
      value: ca-bundle.crt
    - name: subdirectory
      value: ""
    - name: sparseCheckoutDirectories
      value: ""
    - name: deleteExisting
      value: "true"
    - name: httpProxy
      value: ""
    - name: httpsProxy
      value: ""
    - name: noProxy
      value: ""
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:868966ef9d4b54952d8a74eb83bba40eb1f52c0148994fa704efd0e3797c61c5
    - name: userHome
      value: /home/git
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: build-and-push
    params:
    - name: IMAGE
      value: $(params.IMAGE__NAME)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:b48f410efa0ff8ab0db6ead420a5d8d866d64af846fece5efb185230d7ecf591
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./Dockerfile
    - name: CONTEXT
      value: $(params.CONTEXT_DIR)
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: BUILD_EXTRA_ARGS
      value: ""
    - name: PUSH_EXTRA_ARGS
      value: ""
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  - name: rollout-restart
    params:
    - name: APP_NAME
      value: $(params.APP_NAME)
    - name: NAMESPACE
      value: app1-dev
    runAfter:
    - build-and-push
    taskRef:
      kind: Task
      name: rollout-restart
  workspaces:
  - name: workspace
